apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      name: my-blue-app
  template:
    metadata:
      labels:
        name: my-blue-app
    spec:
      containers:
      - name: blue-container  # Add a name for the container
        image: remyars/blue-image:latest
        ports:
        - containerPort: 80
          protocol: TCP
